- alias: All switches off (long press)
  trigger:
    platform: event
    event_type: xiaomi_aqara.click
    event_data:
      entity_id: binary_sensor.switch_158d0001e88780
      click_type: double
  action:
      service: switch.turn_off
      entity_id: group.indoor_switches