- alias: Night light (single button press)
  trigger:
    platform: event
    event_type: xiaomi_aqara.click
    event_data:
      entity_id: binary_sensor.switch_158d0001e88780
      click_type: single
  action:
      - service: switch.turn_on
        entity_id: switch.kitchen_cupboard_lights
      - service: switch.turn_on
        entity_id: switch.stair_lights
      - delay: 00:03:00
      - service: switch.turn_off
        entity_id: switch.kitchen_cupboard_lights
      - service: switch.turn_off
        entity_id: switch.stair_lights