# CCTV Motion detection
  - alias: "Front CCTV motion detect (at home)"
    initial_state: true
    hide_entity: false
    trigger:
      platform: state
      entity_id: input_boolean.front_camera
      from: 'off'
      to: 'on'
    condition:
      condition: and
      conditions:
        - condition: time
          after: '07:00:00'
          before: '23:00:00'
        - condition: template
          value_template: >
            {% if is_state('device_tracker.duncan', 'home') %}
              true
            {% elif is_state('device_tracker.beth', 'home') %}
              true
            {% else %}
              false
            {% endif %}
    action:
      - service: media_player.volume_set
        data_template:
          entity_id: media_player.living_room_speaker
          volume_level: 0.5
      - service: tts.google_say
        data_template:
          entity_id: media_player.living_room_speaker
          message: 'Movement detected in the front garden.' 
      - service: notify.pushbullet
        data:
          message: "Movement deteced in the front garden!"          
 
  - alias: "Front CCTV motion detect (not at home)"
    initial_state: true
    hide_entity: false
    trigger:
      platform: state
      entity_id: input_boolean.front_camera
      from: 'off'
      to: 'on'
    condition:
      condition: template
      value_template: >
        {% if is_state('device_tracker.duncan', 'away') %}
          true
        {% elif is_state('device_tracker.beth', 'away') %}
          true
        {% else %}
          false
        {% endif %}
    action:
      - service: notify.pushbullet
        data:
          message: "Movement deteced in the front garden!"
          
# Alarm conditions
  - alias: "Alarm set"
    initial_state: true
    trigger:
      - platform: state
        entity_id: device_tracker.duncan
        from: 'home'
        to: 'away'
        for: 
          minutes: 5
      - platform: state
        entity_id: device_tracker.beth
        from: 'home'
        to: 'away'
        for: 
          minutes: 5
    condition:
      condition: template
      value_template: >
        {% if is_state('device_tracker.duncan', 'away') %}
          true
        {% elif is_state('device_tracker.beth', 'away') %}
          true
        {% else %}
          false
        {% endif %}          
    action:
      - service: alarm_control_panel.alarm_arm_away
        data:
          entity_id: alarm_control_panel.ha_alarm
          code: !secret alarm_code
      - service: notify.pushbullet
        data:
          message: "The alarm is set!"
 
  - alias: "Alarm unset"
    initial_state: true
    trigger:
      - platform: state
        entity_id: device_tracker.duncan
        from: 'away'
        to: 'home'
      - platform: state
        entity_id: device_tracker.duncan
        from: 'away'
        to: 'home'
    action:
      - service: alarm_control_panel.alarm_disarm
        data:
          entity_id: alarm_control_panel.ha_alarm
          code: !secret alarm_code

          
# Alarm triggers
  - alias: "Alarm (Door sensors)"
    initial_state: false
    trigger:
      - platform: state
        entity_id: binary_sensor.door_window_sensor_158d0002b5b396
        from: 'off'
        to: 'on'
      - platform: state
        entity_id: binary_sensor.door_window_sensor_158d0002b7b04c
        from: 'off'
        to: 'on'
    condition:
      condition: state
      entity_id: alarm_control_panel.home_alarm
      state: armed_away
    action:
      - delay: 00:00:30
      - service: notify.pushbullet
        data:
          message: "The alarm has been triggered!"
         